pipeline {
    agent any
    environment {
        app = 'gitground'
        version = '1.0'
    }
    stages {
        
        stage('checkout') {
            steps {
                gitbranch: 'main', url: 'https://github.com/rpavan12/PROJECTS.git'
            }
        }

        stage('test') {
            steps {
                sh 'echo "Testing the application..."'
            }
        }
}